---

#Pass stack_file from command line

- hosts: target
  become: true
  pre_tasks:
    - fail:
        msg: "Define stack_file, pass it from command line"
      when: stack_file is not defined

    - name: set some variable
      set_fact:
        use_volumes: False
        stack: {}

    - name: load yaml as hash
      include_vars:
        file: "{{ stack_file }}"
        name: original_stack
    
    - name: extract custom properties
      set_fact:
        HA_at_homes: "{{ original_stack['HA_at_homes'] }}"
        stack_name: "{{ (stack_file | basename | splitext)[0] }}"

    - name: remove our proprieties
      set_fact:
        stack: "{{stack |combine({item.key: item.value})}}"
      when: item.key not in ['HA_at_homes']
      with_dict: "{{ original_stack }}"

    - name: find if volumes are used
      set_fact:
        use_volumes: True
      when: item.key in ['volumes']
      with_dict: "{{ stack }}"

    - name: setup volumes 
      include_tasks: tasks/volumesSetup.yml
      when: use_volumes

    - name: setup stack to use traefik
      include_tasks: tasks/traefikSetup.yml
      when: HA_at_homes['use_traefik']

    - name: setup stack to use dynu client
      include_tasks: tasks/dynuSetup.yml

    - debug:
        var: stack
  tasks:
    - include_role:
        name: deploy-stack
      vars:
        deploy_stack_stack_hash: "{{ stack }}"
        deploy_stack_stack_name: "{{ stack_name }}"

