---

- hosts: peripheral-raspberry
  become: true
  tasks:
    - include_role:
        name: basicSetup
    - include_role:
        name: dockerRaspbian
      vars:
        no_gluster: true

- hosts: peripheral-raspberry
  become: true
  serial: 1
  tasks:
    - include_role:
        name: docker-swarm

- hosts: peripheral-raspberry
  become: true
  tasks:
    - name: create backend network
      docker_network:
        name: "traefik_backends"
        driver: "overlay"
        attachable: yes
    - include_role:
        name: deploy-service
      run_once: true
      vars:
        name_service: "traefik"
#        image: "arm32v6/traefik"
        image: "traefik"
        volumes:
          - "type=bind,source=/var/run/docker.sock,destination=/var/run/docker.sock"
        additional_args: > 
                          --publish published=80,target=80,mode=host
                          --publish published=443,target=443,mode=host
                          --publish published=8080,target=8080,mode=host
                          --update-delay 10s
                          --update-parallelism 1
                          --restart-condition on-failure
                          --mode global
                          --constraint 'node.role == manager' 
        command: >-
          --api
          --entrypoints='Name:http Address::80'
          --entrypoints='Name:https Address::443'
          --defaultentrypoints=http,https
          --docker
          --docker.swarmMode
          --docker.domain=servep2p.com
          --docker.watch
        networks:
          - "traefik_backends"

