---

- hosts: peripheral-raspberry
  become: true
  tasks:
    - include_role:
        name: basicSetup
    - include_role:
        name: dockerRaspbian
      vars:
        no_gluster: true
    - include_role:
        name: docker-swarm
      vars:
        single_swarm: True
#    - name: create backend network
#      docker_network:
#        name: "{{ HA_at_homes_traefik_backend_network }}"
#        driver: "overlay"
#        attachable: yes
    - name: check network
      command: "docker inspect {{ HA_at_homes_traefik_backend_network }}"
      register: check_net
      changed_when: false
      ignore_errors: yes
    - name: create network
      command: "docker network create --attachable --driver overlay {{ HA_at_homes_traefik_backend_network }}"
      when: check_net is failed

    - include_role:
        name: deploy-service
      vars:
        name_service: "traefik"
#        image: "arm32v6/traefik"
        image: "traefik"
        volumes:
          - "type=bind,source=/var/run/docker.sock,destination=/var/run/docker.sock"
        additional_args: > 
                          --publish published=80,target=80,mode=host
                          --publish published=443,target=443,mode=host
                          --publish published=8080,target=8080,mode=host
                          --update-delay 10s
                          --update-parallelism 1
                          --restart-condition on-failure
                          --mode global
                          --constraint 'node.role == manager' 
        command: >-
          --api
          --entrypoints='Name:http Address::80'
          --entrypoints='Name:https Address::443'
          --defaultentrypoints=http,https
          --docker
          --docker.swarmMode
          --docker.domain=servep2p.com
          --docker.watch
        networks:
          - "traefik_backends"

