

#TODO 
# mettere nome stack prima di ogni volume, perche' durante il deploy cambia il nome


- name: insert sync deployer in the services
  set_fact:
    stack: "{{ stack|combine({'services':{ 'volume_sync_deployer' : {item.0: item.1}}}, recursive=True) }}"
  with_together:
    - ['image' ]
    - [ "{{ HA_at_homes_volume_sync_deployer_image }}" ]

- name: insert environment for sync deployer 
  set_fact:
    stack: "{{ stack|combine({'services':{ 'volume_sync_deployer' : { 'environment' : {item.0: item.1}}}}, recursive=True) }}"
  with_together:
    - ['VOLUMESYNC_NAME', 
       'VOLUMESYNC_KEY',
       'VOLUMESYNC_VOLUMES', 
       'VOLUMESYNC_AUTH',
       'VOLUMESYNC_SERVERIMAGE',
       'VOLUMESYNC_PROXYIMAGE',
       'VOLUMESYNC_STACK',
       'VOLUMESYNC_SERVICE',
       'VOLUMESYNC_PORT',
       'VOLUMESYNC_TRAEFIKNETWORK',
       'PYTHONUNBUFFERED']
    - [ "{{ inventory_hostname|regex_replace('\\.', '') }}",
        "{{ HA_at_homes['csync2_key'] }}",
        "{{ stack['volumes']|map('regex_replace', '(.*)',stack_name + '_\\1')|join(',') }}",
        "{{ HA_at_homes['proxy_auth'] }}",
        "{{ HA_at_homes_volume_server_image }}",
        "{{ HA_at_homes_volume_proxy_image }}",
        "{{ stack_name }}",
        "{{ HA_at_homes['node_name'] }}.{{ HA_at_homes['domain_name'] }}",
        "{{ HA_at_homes['exposed_port'] }}",
        "{{ HA_at_homes_traefik_backend_network }}",
        "1"]

- name: insert /var/run/docker.sock for sync deployer
  set_fact:
    stack: "{{ stack|combine({'services':{ 'volume_sync_deployer' : { 'volumes' : [{ 'type' : 'bind', 'source' : '/var/run/docker.sock', 'target':'/var/run/docker.sock'}] }}}, recursive=True) }}"


- name: insert dependency for sync deployer
  set_fact:
    stack: "{{ stack|combine({'services':{ 'volume_sync_deployer' : { 'depends_on' : ['dynu_client'] }}}, recursive=True) }}"
