
# HA_at_homes_volumes_type:
# HA_at_homes_volumes_dir:

- include_tasks: "setLocalVolume.yml"
  vars: 
    volume_name: "{{ item }}"
  with_items: "{{ stack['volumes'] }}"
  when: HA_at_homes_volumes_type == 'local'

- include_tasks: "setNfsVolume.yml"
  vars: 
    volume_name: "{{ item }}"
  with_items: "{{ stack['volumes'] }}"
  when: HA_at_homes_volumes_type == 'nfs'





